[".local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/zsh-users/zsh-autosuggestions/85919cd1ffa7d2d5412f6d3fe437ebdbeeec4fc5/zsh-autosuggestions.zsh"
checksum.sha256 = "eec7ba8f7a71414ace0ea0fab0908d005b24cf65d83b169c0ff97815d3cfc51a"

[".local/share/zsh/plugins/zsh-completions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-completions/archive/b5e8e0a22deb05a807bb8655aef809a29f3cffed.tar.gz"
checksum.sha256 = "2a7a140e2698f39fb215a0ea86694c8c59ad51c97133cf3f2709c46dfe28bf34"
exact = true
stripComponents = 1
include = ["*/src/**"]

[".local/share/zsh/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/0bfcb582e71d3abe604ce67bc0fe5a21f377507e.tar.gz"
checksum.sha256 = "898766fe913588bb8e022ccddc263fc618a1308da914d397cd8b0c305b8ad3aa"
exact = true
stripComponents = 1
include = ["*/.revision-hash", "*/.version", "*/zsh-syntax-highlighting.zsh", "*/highlighters", "*/highlighters/*", "*/highlighters/*/*-highlighter.zsh"]
