repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: mise exec -- gitleaks git --staged --config .gitleaks.toml --redact --no-banner -v
        language: system
        pass_filenames: false

      - id: shellcheck
        name: shellcheck
        entry: mise exec -- shellcheck
        language: system
        files: '^(bootstrap\.sh|\.chezmoiscripts/.*\.sh|dot_config/private_git/template/hooks/executable_pre-commit)$'

      - id: chezmoi-templates
        name: chezmoi templates
        entry: mise run render
        language: system
        files: '\.tmpl$'
        pass_filenames: false
