# Native libraries, services, fonts, apps, and CLIs not in .config/mise/config.toml.
# `chezmoi apply` runs `brew bundle` whenever this file changes; `mise run doctor` lists drift.
brew "automake"
brew "btop"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "dust"
brew "eza"
brew "ffmpeg"
brew "gcc"
brew "git"
brew "git-filter-repo"
brew "graphviz"
brew "grpcurl"
brew "latexml"
brew "ninja"
brew "pandoc"
brew "pkgconf"
brew "poppler"
brew "postgresql@17", restart_service: :changed
brew "rsync"
brew "tectonic"
brew "tesseract"
brew "tmux"
brew "tree"
brew "wget"
cask "basictex"
cask "codex"
cask "font-sf-mono"
cask "ghostty"
cask "ngrok"
cask "orbstack"
cask "tailscale-app"
